// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv735PqxI6lG8JUC_EEZRt5fnEVcea374',
    appId: '1:456877659015:web:55fc4051fb0fb8fdf7b922',
    messagingSenderId: '456877659015',
    projectId: 'libseat-smnr26',
    authDomain: 'libseat-smnr26.firebaseapp.com',
    storageBucket: 'libseat-smnr26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8llE_vtCHV4I3khAsFqTrJts6Vzp9ZwA',
    appId: '1:456877659015:android:e46dda102d89e47ef7b922',
    messagingSenderId: '456877659015',
    projectId: 'libseat-smnr26',
    storageBucket: 'libseat-smnr26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLd-blpDE1MO8Nwc2lKe358O7GDVhxvT4',
    appId: '1:456877659015:ios:503d139b9c50823af7b922',
    messagingSenderId: '456877659015',
    projectId: 'libseat-smnr26',
    storageBucket: 'libseat-smnr26.firebasestorage.app',
    iosBundleId: 'com.example.librarySeatTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLd-blpDE1MO8Nwc2lKe358O7GDVhxvT4',
    appId: '1:456877659015:ios:503d139b9c50823af7b922',
    messagingSenderId: '456877659015',
    projectId: 'libseat-smnr26',
    storageBucket: 'libseat-smnr26.firebasestorage.app',
    iosBundleId: 'com.example.librarySeatTrackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv735PqxI6lG8JUC_EEZRt5fnEVcea374',
    appId: '1:456877659015:web:7d669cffb5581b32f7b922',
    messagingSenderId: '456877659015',
    projectId: 'libseat-smnr26',
    authDomain: 'libseat-smnr26.firebaseapp.com',
    storageBucket: 'libseat-smnr26.firebasestorage.app',
  );
}
